### ISSUE TITLE
Add labelHandler kind = "ASSIGN"

### ISSUE THREAD

**Issue by theanurin** [edgebus/edgebus#10]
# Add labelHandler kind = "ASSIGN"

Implement label assigner

## Use Case

In case when a `egress` attached to several topics, I want to use Egress Filter Label feature to select messages by a topic. So I want to assign some label that will identify the topic.

## Expected Configuration

```toml
[[edgebus.setup.topic]]
	index = "TOPC86e993be253f46f6b9b9542c544b8cf9"
	name = "fireblocks-production"
	description = "Fireblocks callbacks"
	mediaType = "application/json"
	[[edgebus.setup.topic.labelHandler]]
		index = "LBHDc3190fcbf16c4c41ac7e846daefc8d2c"
		kind = "EXTERNAL_PROCESS"
		path="/etc/edgebus/labels_handler/fireblocks_label_handler.py"
	[[edgebus.setup.topic.labelHandler]]
		index = "LBHD2bbdced1cc844bdab89ccc8f5e846110"
		kind = "ASSIGN"
		label="production"
```
